Numa\DOAAdminBundle\Entity\Item:
    type: entity
    table: item
    repositoryClass: Numa\DOAAdminBundle\Repository\ItemRepository
    indexes:
        featured:
            columns: [ featured ]
        active:
            columns: [ active ]
        activefeatured:
            columns: [ featured,active ]
        year:
            columns: [ year ]
        body_style:
            columns: [ body_style ]
        make:
            columns: [ make ]
        model:
            columns: [ model ]
        VIN:
            columns: [ VIN ]
        transmission:
            columns: [ body_style ]
        keywords:
            columns: [ keywords ]
        floor_plan:
            columns: [ floor_plan ]
        stock_nr:
            columns: [ stock_nr ]
        sold:
            columns: [ sold ]
        type:
            columns: [ type ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sid:                                     
              type: string
              length: 255
              nullable: true
        feed_id:                                     
              type: integer
              nullable: true
        category_id:                                     
              type: integer
              nullable: true
        user_id:                                     
              type: integer
              nullable: true
        seo_id:
              type: integer
              nullable: true
        active:                                     
              type: boolean
              default: 0
              nullable: true
        moderation_status:                                     
              type: string
              length: 255
              nullable: true
        keywords:
              type: string
              length: 255
              nullable: true
        sold:                                     
              type: boolean
              default: 0
              nullable: true
        featured:                                     
              type: boolean
              default: 0
              nullable: true
        views:                                     
              type: integer
              nullable: true
        pictures:                                     
              type: integer
              nullable: true
        activation_date:
              type: datetime
              nullable: true
        expiration_date:
              type: datetime
              nullable: true
        featured_last_showed:
              type: datetime
              nullable: true
        date_created:
              type: datetime
              nullable: true

        date_updated:
              type: datetime
              nullable: true
        auto_extend:
              type: boolean
              nullable: true        
        feature_highlighted:
              type: boolean
              default: 0    
              nullable: true       
        feature_slideshow:
              type: boolean
              default: 0           
              nullable: true       
        feature_youtube:
              type: boolean
              default: 0    
              nullable: true       
        last_user_ip:
              type: string
              length: 32
              nullable: true
        dealer_id:                                     
              type: integer
              nullable: true
        body_style:
              type: string
              length: 255
              nullable: true
        body_description:
              type: string
              length: 255
              nullable: true
        model:
              type: string
              length: 255
              nullable: true
        price:
              type: bigint
              nullable: true
        year:
              type: integer
              nullable: true
        type:
              type: string
              length: 255
              nullable: true
        floor_plan:
              type: string
              length: 255
              nullable: true
        ag_application:
              type: string
              length: 255
              nullable: true
        postal:
              type: string
              length: 255
              nullable: true
        city:
              type: string
              length: 255
              nullable: true
        address:
              type: string
              length: 255
              nullable: true
        status:
              type: string
              length: 255
              nullable: true
        stock_nr:
              type: string
              length: 255
              nullable: true
        mileage:
              type: bigint
              nullable: true
        VIN:
              type: string
              length: 255
              nullable: true
        engine_VIN:
              type: string
              length: 255
              nullable: true
        trailer_VIN:
              type: string
              length: 255
              nullable: true
        transmission:
              type: string
              length: 255
              nullable: true
        retail_price:
              type: float
              nullable: true
        price:
              type: float
              nullable: true
        make:
              type: string
              length: 255
              nullable: true
        model:
              type: string
              length: 255
              nullable: true
        engine:
              type: string
              length: 255
              nullable: true
        engine_type:
              type: string
              length: 255
              nullable: true
        fuel_type:
              type: string
              length: 255
              nullable: true
        drive_type:
              type: string
              length: 255
              nullable: true  
        interior_color:
              type: string
              length: 255
              nullable: true
        exterior_color:
              type: string
              length: 255
              nullable: true
        videoId:            
              type: string
              length: 255
              nullable: true  
        trim:
              type: string
              length: 255
              nullable: true 
        doors:
              type: string
              length: 255
              nullable: true            
        seller_comment:
              type: text
              nullable: true
        seller_comment_1:
              type: text
              nullable: true
        seller_comment_2:
              type: text
              nullable: true
        seller_comment_active:
              type: smallint
              nullable: true
        length:
              type: string
              length: 255
              nullable: true
        weight:
              type: string
              length: 255
              nullable: true
        hull_design:
              type: string
              length: 255
              nullable: true              
        beam:
              type: string
              length: 255
              nullable: true              
        steering:
              type: string
              length: 255
              nullable: true              
        steering_type:
              type: string
              length: 255
              nullable: true              
        of_hours:
              type: string
              length: 255
              nullable: true              
        passengers:
              type: string
              length: 255
              nullable: true              
        trailer:
              type: string
              length: 255
              nullable: true              
        battery:
              type: string
              length: 255
              nullable: true              
        fuel_capacity:
              type: string
              length: 255
              nullable: true              
        fuel_system:
              type: string
              length: 255
              nullable: true               
        ignition:
              type: string
              length: 255
              nullable: true               
        gears:
              type: string
              length: 255
              nullable: true               
        displacement:
              type: string
              length: 255
              nullable: true               
        chassis:
              type: string
              length: 255
              nullable: true               
        chassis_type:
              type: string
              length: 255
              nullable: true               
        sleeps:
              type: string
              length: 255
              nullable: true               
        slide_outs:
              type: string
              length: 255
              nullable: true               
        flooring:
              type: string
              length: 255
              nullable: true               
        floor_plan:
              type: string
              length: 255
              nullable: true               
        class:
              type: string
              length: 255
              nullable: true               
        operator_station:
              type: string
              length: 255
              nullable: true               
        speed_forward:
              type: string
              length: 255
              nullable: true               
        speed_reverse:
              type: string
              length: 255
              nullable: true               
        tire_size:
              type: string
              length: 255
              nullable: true               
        tire_equipment:
              type: string
              length: 255
              nullable: true               
        cutting_width:
              type: string
              length: 255
              nullable: true               
        cooling_system:
              type: string
              length: 255
              nullable: true               
        horsepower:
              type: integer
              nullable: true
        pto_horsepower:
              type: integer
              nullable: true
        DBR_horsepower:
              type: integer
              nullable: true
        awnings:
              type: string
              length: 255
              nullable: true
        width:
              type: string
              length: 255
              nullable: true
        height:
              type: string
              length: 255
              nullable: true
        mpgCity:
              type: string
              length: 255
              nullable: true
        mpgHighway:
              type: string
              length: 255
              nullable: true
        iw_no:
              type: string
              length: 255
              nullable: true
        other:
              type: text
              nullable: true
        invoice_nr:
              type: string
              length: 255
              nullable: true
        invoice_date:
              type: datetime
              nullable: true
        invoice_amount:
              type: float
              nullable: true
        discount1:
              type: float
              nullable: true
        discount2:
              type: float
              nullable: true
        sale_amount:
              type: float
              nullable: true
        torque:
              type: string
              length: 255
              nullable: true
        brakes:
              type: string
              length: 255
              nullable: true
        wheels:
              type: string
              length: 255
              nullable: true
        compression_ratio:
              type: float
              nullable: true
        frame:
              type: string
              length: 255
              nullable: true
        suspension:
              type: string
              length: 255
              nullable: true
        ground_clereance:
              type: string
              length: 255
              nullable: true
        fresh_water_capacity:
              type: integer
              nullable: true
        black_water_capacity:
              type: integer
              nullable: true
        gray_water_capacity:
              type: integer
              nullable: true
        hitch_weight:
              type: float
              nullable: true
        remotes:
              type: string
              length: 255
              nullable: true
        cover_photo:
              type: string
              length: 255
              nullable: true
        expense_1_descrip:
              type: string
              length: 255
              nullable: true
        expense_1_amt:
              type: float
              nullable: true
        expense_2_descrip:
              type: string
              length: 255
              nullable: true
        expense_2_amt:
              type: float
              nullable: true
        expense_3_descrip:
              type: string
              length: 255
              nullable: true
        expense_3_amt:
              type: float
              nullable: true
        expense_4_descrip:
              type: string
              length: 255
              nullable: true
        expense_4_amt:
              type: float
              nullable: true
        total_cost:
              type: float
              nullable: true
        sale_id:
              type: integer
              nullable: true
        vindecoder:
              type: text
              nullable: true
        archive_status:
              type: string
              length: 32
              nullable: true
        archived_date:
              type: datetime
              nullable: true
        sold_date:
              type: datetime
              nullable: true
        qb_item_id:
              type: integer
              nullable: true
        sub_category_type:
              type: string
              length: 255
              nullable: true
        feed_kijiji_include:
            type: boolean
            options:
               default: false
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
    manyToOne:
        Category:
            targetEntity: Category
            inversedBy: Item
            joinColumn:
                name: category_id
                referencedColumnName: id
        Importfeed:
            targetEntity: Importfeed
            inversedBy: Item
            cascade: ["persist"]
            joinColumn:
                name: feed_id
                referencedColumnName: id
        User:
            targetEntity: User
            inversedBy: Item
            cascade: ["persist"]
            joinColumn:
                name: user_id
                referencedColumnName: id
        Dealer:
            targetEntity: Catalogrecords
            inversedBy: Item
            cascade: ["persist"]
            joinColumn:
                name: dealer_id
                referencedColumnName: id

    oneToMany:
        ItemField:
            targetEntity: ItemField
            mappedBy: Item
            cascade: ["persist","remove"]
            joinColumn:
                name: item_id
                referencedColumnName: id
                onDelete: cascade
        UserItem:
            targetEntity: UserItem
            mappedBy: Item
            cascade: ["persist","remove"]
            joinColumn:
                name: item_id
                referencedColumnName: id
                onDelete: cascade
        Billing:
            targetEntity: Numa\DOADMSBundle\Entity\Billing
            mappedBy: Item
            cascade: ["persist"]
            joinColumn:
                name: item_id
                referencedColumnName: id
                onDelete: cascade
    oneToOne:
        Sale:
            targetEntity: Numa\DOADMSBundle\Entity\Sale
            cascade: ["persist","remove"]
            inversedBy: Item
            fetch: EAGER
            joinColumn:
                name: sale_id
                referencedColumnName: id
