client:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Client:index" }

client_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:Client:show" }

client_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:Client:new" }

client_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:Client:create" }
    requirements: { _method: post }

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:Client:edit" }

client_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:Client:update" }
    requirements: { _method: post|put }

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:Client:delete" }
    requirements: { _method: post|delete }
