dealercomponent:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:index" }

dealercomponent_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:show" }

dealercomponent_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:new" }

dealercomponent_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:create" }
    requirements: { _method: post }

dealercomponent_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:edit",_dashboard:"DMS" }

dealercomponent_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:update" }
    requirements: { _method: post|put }

dealercomponent_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:DealerComponent:delete" }
    requirements: { _method: post|delete }
