note:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:Note:index" }

note_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:Note:show" }

note_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:Note:new" }

note_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:Note:create" }
    requirements: { _method: post }

note_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:Note:edit" }

note_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:Note:update" }
    requirements: { _method: post|put }

note_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:Note:delete" }
    requirements: { _method: post|delete }
