servicerequest:
    path:     /
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:index" }

servicerequest_show:
    path:     /{id}/show
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:show" }

servicerequest_new:
    path:     /new
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:new" }

servicerequest_create:
    path:     /create
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:create" }
    requirements: { _method: post }

servicerequest_edit:
    path:     /{id}/edit
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:edit" }

servicerequest_update:
    path:     /{id}/update
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:update" }
    requirements: { _method: post|put }

servicerequest_delete:
    path:     /{id}/delete
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:delete" }
    requirements: { _method: post|delete }

servicerequest_mass_delete:
    path:     /delete
    defaults: { _controller: "NumaDOADMSBundle:ServiceRequest:massDelete2" }