numa_doa_admin_homepage:
    pattern:  /
    defaults: { _controller: NumaDOAAdminBundle:Default:index }
NumaDOAAdminBundle_catalogs:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/catalogrecords.yml"
        prefix:   /catalogs
NumaDOAAdminBundle_importfeed:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/importfeed.yml"
        prefix:   /featuredimport
NumaDOAAdminBundle_categories:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/category.yml"
        prefix:   /categories
NumaDOAAdminBundle_import_mapping:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/importmapping.yml"
        prefix:   /import_mapping
NumaDOAAdminBundle_items:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/item.yml"
        prefix:   /items
NumaDOAAdminBundle_item_field:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/itemfield.yml"
        prefix:   /itemsfield
NumaDOAAdminBundle_user:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/user.yml"
        prefix:   /user
NumaDOAAdminBundle_user_group:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/usergroup.yml"
        prefix:   /user_group
feed_api:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/feed_api.yml"
        prefix:   /feed_api
command_log:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/command_log.yml"
        prefix:   /command_log        
iauto:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/iauto.yml"
        prefix:   /iauto
NumaDOAAdminBundle_coupon:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/coupon.yml"
        prefix:   /coupon
NumaDOASettingsBundle_setting:
        resource: "@NumaDOASettingsBundle/Resources/config/routing/setting.yml"
        prefix:   /setting
NumaDOAAdminBundle_imagecarousel:
        resource: "@NumaDOAAdminBundle/Resources/config/routing/imagecarousel.yml"
        prefix:   /imagecarousel
NumaDOAModuleBundle_page:
        resource: "@NumaDOAModuleBundle/Resources/config/routing/page.yml"
        prefix:   /page
